//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseno_Desarrollo_Grupo5.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA
    {
        public int ID_BITACORA { get; set; }
        public int ID_USUARIO { get; set; }
        public string ACCION { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
