//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Proyecto_Diseno_Desarrollo_Grupo5.EF
{

    public partial class BITACORA
    {
        public int ID_BITACORA { get; set; }
        public int ID_USUARIO { get; set; }
        public string ACCION { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA { get; set; }
        public string MODULO { get; set; }
        public string ID_REGISTRO_AFECTADO { get; set; }
        public string RESULTADO { get; set; }

        public virtual USUARIOS USUARIOS { get; set; }
    }
}
