//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseno_Desarrollo_Grupo5.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESPERDICIOS_MATERIAL
    {
        public int ID_DESPERDICIO { get; set; }
        public int ID_MATERIAL { get; set; }
        public decimal CANTIDAD_DESPERDICIADA { get; set; }
        public string REUTILIZABLE { get; set; }
        public decimal CANTIDAD_REUTILIZADA { get; set; }
        public string MOTIVO { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    
        public virtual MATERIALES MATERIALES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
