//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseno_Desarrollo_Grupo5.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVOLUCIONES
    {
        public int ID_DEVOLUCION { get; set; }
        public int ID_VENTA { get; set; }
        public string MOTIVO { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual VENTAS VENTAS { get; set; }
    }
}
