//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseno_Desarrollo_Grupo5.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVOLUCIONES
    {
        public int ID_DEVOLUCION { get; set; }
        public int ID_VENTA { get; set; }
        public string MOTIVO { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual VENTAS VENTAS { get; set; }
    }
}
