//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseno_Desarrollo_Grupo5.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GARANTIAS
    {
        public int ID_GARANTIA { get; set; }
        public int ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public int DURACION_MESES { get; set; }
        public string CONDICIONES { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
