//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseno_Desarrollo_Grupo5.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOS_INVENTARIO
    {
        public int ID_MOVIMIENTO { get; set; }
        public int ID_MATERIAL { get; set; }
        public string TIPO_MOVIMIENTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public System.DateTime FECHA { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual MATERIALES MATERIALES { get; set; }
    }
}
