//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseno_Desarrollo_Grupo5.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOS_INVENTARIO
    {
        public int ID_MOVIMIENTO { get; set; }
        public int ID_MATERIAL { get; set; }
        public string TIPO_MOVIMIENTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public System.DateTime FECHA { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual MATERIALES MATERIALES { get; set; }
    }
}
