//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Proyecto_Diseno_Desarrollo_Grupo5.EF
{

    public partial class PAGOS
    {
        public int ID_PAGO { get; set; }
        public int ID_VENTA { get; set; }
        public decimal MONTO { get; set; }
        public string METODO { get; set; }
        public string REFERENCIA { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }

        public virtual USUARIOS USUARIOS { get; set; }
        public virtual VENTAS VENTAS { get; set; }
    }
}
