//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseno_Desarrollo_Grupo5.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDORES()
        {
            this.MATERIALES = new HashSet<MATERIALES>();
        }
    
        public int ID_PROVEEDOR { get; set; }
        public string NOMBRE { get; set; }
        public string CONTACTO { get; set; }
        public string TELEFONO { get; set; }
        public int ID_ESTADO { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIALES> MATERIALES { get; set; }
    }
}
