//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Diseno_Desarrollo_Grupo5.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.BITACORA = new HashSet<BITACORA>();
            this.DESPERDICIOS_MATERIAL = new HashSet<DESPERDICIOS_MATERIAL>();
        }
    
        public int ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
        public string CONTRASENA { get; set; }
        public int ID_ROL { get; set; }
        public int ID_ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BITACORA> BITACORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESPERDICIOS_MATERIAL> DESPERDICIOS_MATERIAL { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual ROLES ROLES { get; set; }
    }
}
